version: '3.8'

networks:
  external:
    driver: bridge

services:
  db:
    build: ./db/.

    networks:
      - external
    container_name: conversiondb

    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256

    ports:
      - 5432:5432
